import React from 'react';
import { 
  LayoutDashboard, 
  BookOpen, 
  Users, 
  FileText, 
  Settings, 
  LogOut, 
  Plus, 
  MoreVertical,
  Trash2,
  Edit,
  Check,
  X,
  Search,
  BrainCircuit,
  FileSpreadsheet,
  Link as LinkIcon,
  FileQuestion,
  GraduationCap,
  Mail,
  Shield,
  UsersRound,
  Eye,
  EyeOff,
  Mic,
  Square,
  Volume2,
  Zap,
  Cloud,
  Upload
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Courses: BookOpen,
  Users: Users,
  Materials: FileText,
  FileText: FileText, // Added to expose generic FileText icon
  CMS: FileSpreadsheet,
  Settings: Settings,
  Logout: LogOut,
  Plus: Plus,
  More: MoreVertical,
  Delete: Trash2,
  Edit: Edit,
  Check: Check,
  Close: X,
  Search: Search,
  AI: BrainCircuit,
  Link: LinkIcon,
  Quiz: FileQuestion,
  Student: GraduationCap,
  Mail: Mail,
  Role: Shield,
  Shield: Shield,
  Class: UsersRound,
  UsersRound: UsersRound,
  Eye: Eye,
  EyeOff: EyeOff,
  Mic: Mic,
  Stop: Square,
  Volume: Volume2,
  Active: Zap,
  Cloud: Cloud,
  Upload: Upload
};